services:
  site:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: mibeko-site
    restart: unless-stopped
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.mibeko-site.rule=Host(`${MIBEKO_SITE_HOST:-mibeko.fr}`)"
      - "traefik.http.routers.mibeko-site.entrypoints=websecure"
      - "traefik.http.routers.mibeko-site.tls.certresolver=myresolver"
      - "traefik.http.routers.mibeko-site.priority=1"

      - "traefik.http.services.mibeko-site.loadbalancer.server.port=80"

networks:
  proxy:
    external: true